name: AutoTwttelgrm

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 999

    steps:
    - name: Instala Paquetes Necesarios
      run: |
        cmd /c pip install requests
        cmd /c pip install m3u8
        cmd /c pip install aiohttp
        cmd /c pip install telegram-upload
        cmd /c md "C:\1Twitch"
        cmd /c md "C:\Users\administrator\.config"
    - name: Descargar Archivos Necesarios
      run: |
        Invoke-WebRequest https://drive.google.com/uc?id=$Env:SESSION_DATA -OutFile "C:\Users\administrator\.config\data.zip"
        Invoke-WebRequest https://raw.githubusercontent.com/henri4men/AutoTwttelgrm1/main/DuplTwi_R0_0_var.py -OutFile "C:\1Twitch\DuplTwi_R0_0_var.py"
        Invoke-WebRequest https://raw.githubusercontent.com/henri4men/AutoTwttelgrm1/main/DuplTwi_R0_0.py -OutFile "C:\1Twitch\DuplTwi_R0_0.py"
      env:
        SESSION_DATA: ${{ secrets.SESSION_DATA_1 }}
    - name: Descomprimir Datos
      run: |
        cd "C:\Users\administrator\.config"
        Expand-Archive data.zip -DestinationPath "C:\Users\administrator\.config"
    - name: Ejecutar
      run: |
        cd "C:\1Twitch"
        python DuplTwi_R0_0.py $Env:CHNLS_LINKS 1260712266,1261340779,1261409583,1261560096,1261384661
      env:
        CHNLS_LINKS: ${{ secrets.CHNLS_LINKS }}
